language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
install:
 - npm install
script:
 - npm run semantic-release-pre
 - npm run build
 - npm run cover 
after_success:
  - npm run publish
  - npm run travis-deploy-once
  - npm run semantic-release-post
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

# Send coverage data to Coveralls
after_script: 
- "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"